# Requirements to execute this CI Pipeline
# * Register gitlab-runner with shell executor
# * Install docker with docker compose plugin on gitlab-runner's host
# * Grant permissions to gitlab-runner to execute docker

stages:
  - build
  - test

before_script:
  - docker version

###############################################################################
#### Build stage ##############################################################
###############################################################################

build-backend:
  stage: build
  script:
    - docker compose build jobmon_backend --pull

build-frontend:
  stage: build
  script:
    - docker compose build jobmon_frontend --pull

###############################################################################
#### Test stage ###############################################################
###############################################################################

vetting-backend:
  needs:
    - build-backend
  stage: test
  script:
    - docker build -t jobmon-backend_vetting --target vetting --pull backend
    - docker run --name jobmon-backend_vetting --rm jobmon-backend_vetting

staticchecking-backend:
  needs:
    - build-backend
  stage: test
  script:
    - docker build -t jobmon-backend_staticchecking --target staticchecking --pull backend
    - docker run --name jobmon-backend_staticchecking --rm jobmon-backend_staticchecking

test-backend:
  needs:
    - build-backend
  stage: test
  before_script:
    - docker rm jobmon-backend_reporter || true
  after_script:
    - docker rm jobmon-backend_reporter
  script:
    - docker build -t jobmon-backend_reporter --target reporter --pull backend
    - docker run --name jobmon-backend_reporter jobmon-backend_reporter
    - docker cp jobmon-backend_reporter:/app/report_backend.xml ./
  artifacts:
    # Artifact to safe the test results and visualize them in gitlab
    when: always
    reports:
      junit:
        - report_backend.xml

test-frontend:
  needs:
    - build-frontend
  stage: test
  before_script:
    - docker rm jobmon-frontend_reporter || true
  after_script:
    - docker rm jobmon-frontend_reporter
  script:
    - docker build -t jobmon-frontend_reporter --target reporter --pull frontend
    - docker run --name jobmon-frontend_reporter jobmon-frontend_reporter
    - docker cp jobmon-frontend_reporter:/app/report_frontend.xml ./
  artifacts:
    # Artifact to safe the test results and visualize them in gitlab
    when: always
    reports:
      junit:
        - report_frontend.xml
