# Requirements to execute this CI Pipeline
# * Register gitlab-runner with shell executor
# * Install docker with docker compose plugin on gitlab-runner's host
# * Grant permissions to gitlab-runner to execute docker

stages:
  - build
  - test

before_script:
  - docker version

build-frontend:
  stage: build
  script:
    - docker compose build jobmon_frontend --pull

build-backend:
  stage: build
  script:
    - docker compose build jobmon_backend --pull

test-backend:
  stage: test
  script:
    - docker compose --file docker-compose.test.yml build --pull jobmon_backend_tests
    - docker compose --file docker-compose.test.yml run --rm jobmon_backend_tests

test-frontend:
  stage: test
  script:
    - docker compose --file docker-compose.test.yml build --pull jobmon_frontend_tests
    - docker compose --file docker-compose.test.yml run --rm jobmon_frontend_tests
   