variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  - docker version

build-frontend:
  stage: build
  script:
    - docker compose build jobmon_frontend --pull

build-backend:
  stage: build
  script:
    - docker compose build jobmon_backend --pull