# Requirements to execute this CI Pipeline
# * Register gitlab-runner with shell executor
# * Install docker with docker compose plugin on gitlab-runner's host
# * Grant permissions to gitlab-runner to execute docker

stages:
  - build
  - test

before_script:
  - docker version

build-backend:
  stage: build
  script:
    - docker compose build jobmon_backend --pull

build-frontend:
  stage: build
  script:
    - docker compose build jobmon_frontend --pull

test-backend:
  needs:
    - build-backend
  stage: test
  before_script:
    - docker rm jobmon_backend_test || true
  after_script:
    - docker rm jobmon_backend_test
  script:
    - docker compose --file docker-compose.test.yml build --pull jobmon_backend_tests
    - docker compose --file docker-compose.test.yml run --name jobmon_backend_test jobmon_backend_tests
    - docker cp jobmon_backend_test:/app/report_backend.xml ./
  artifacts:
    when: always
    reports:
      junit:
        - report_backend.xml


test-frontend:
  needs:
    - build-frontend
  stage: test
  before_script:
    - docker rm jobmon_frontend_test || true
  after_script:
    - docker rm jobmon_frontend_test
  script:
    - docker compose --file docker-compose.test.yml build --pull jobmon_frontend_tests
    - docker compose --file docker-compose.test.yml run --name jobmon_frontend_test jobmon_frontend_tests
    - docker cp jobmon_frontend_test:/app/report_frontend.xml ./
    - docker rm jobmon_frontend_test
  artifacts:
    when: always
    reports:
      junit:
        - report_frontend.xml
