services:

  # See: ./frontend/Dockerfile
  # Image based on node:16-alpine
  frontend:
    restart: always
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
        - NEXT_PUBLIC_BACKEND_WS=${BACKEND_WS}
    container_name: JobMonFrontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
      - NEXT_PUBLIC_BACKEND_WS=${BACKEND_WS}
    depends_on:
      - backend

  # See: ./backend/Dockerfile
  # Image based on golang:1.20-alpine
  backend:
    restart: always
    build: ./backend
    container_name: JobMonBackend
    volumes:
      # Configuration config.json needs to be writable to allow backend to add new metrics
      - type: bind
        source: ./backend/config.json
        target: /app/config.json
    depends_on:
      - influxdb
      - postgres

  # DockerHub Page: https://hub.docker.com/_/influxdb
  # GitHub Repository: https://github.com/influxdata/influxdata-docker/
  influxdb:
    restart: always
    image: influxdb
    container_name: JobMonInfluxDB
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    ports:
      - ${INFLUXDB_PORT}:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2

  # DockerHub Page: https://hub.docker.com/_/postgres
  # GitHub Repository: https://github.com/docker-library/postgres
  postgres:
    restart: always
    image: postgres
    container_name: JobMonPostgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  # DockerHub Page: https://hub.docker.com/_/nginx
  # GitHub Repository: https://github.com/nginxinc/docker-nginx
  # Dockerfile for tag latest:
  #   https://github.com/nginxinc/docker-nginx/blob/master/mainline/debian/Dockerfile
  nginx:
    restart: always
    env_file: .env
    image: nginx
    container_name: JobMonNginx
    secrets:
      - source: nginxFullchain
        target: /etc/nginx/certs.d/fullchain.pem
        uid: "nginx"
        gid: "nginx"
        mode: 0400
      - source: nginxPrivkey
        target: /etc/nginx/certs.d/privkey.pem
        uid: "nginx"
        gid: "nginx"
        mode: 0400
      - source: nginxChain
        target: /etc/nginx/certs.d/chain.pem
        uid: "nginx"
        gid: "nginx"
        mode: 0400
    configs:
      - source: nginxDefaultConfig
        target: /etc/nginx/conf.d/default.conf
        uid: "nginx"
        gid: "nginx"
    ports:
      - ${NGINX_HTTP_PORT}:80
      - ${NGINX_HTTPS_PORT}:443
    depends_on:
      - frontend

configs:
  nginxDefaultConfig:
    file: ./nginx/configs/default.conf

secrets:
  nginxFullchain:
    file: ./nginx/secrets/fullchain.pem
  nginxPrivkey:
    file: ./nginx/secrets/privkey.pem
  nginxChain:
    file: ./nginx/secrets/chain.pem
