# Docker configuration for containers used in testing process.
# Those services are mainly used in CI/CD pipeline.
# It is the purpose of both containers to run the corresponding unit-tests for the back- and frontend
services:

  jobmon_frontend_tests:
    restart: no
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
      args:
        # Image based on node:16-alpine
        NODE_RELEASE: "16"
        DEBIAN_RELEASE: bullseye
        # Public URL to access the the backend from the clients webbrowser
        # e.g. https://my-monitor-db.example.org
        NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
        # Public websocket URL to access the backend from the clients webbrowser
        # e.g. wss://my-monitor-db.example.org
        NEXT_PUBLIC_BACKEND_WS: ${BACKEND_WS}
    container_name: jobmon_frontend_test_env
    volumes:
      # Frontend source code
      - type: bind
        source: ./frontend
        target: /app
      # Cache for node modules
      - type: volume
        source: jobmon_frontend_nodes_modules_test
        target: /app/node_modules
      # Cache for next.js folder
      - type: volume
        source: jobmon_frontend_nextjs_test
        target: /app/.next
