# Docker configuration for containers used in testing process.
# Those services are mainly used in CI/CD pipeline.
# It is the purpose of both containers to run the corresponding unit-tests for the back- and frontend
services:

  jobmon_frontend_tests:
    restart: no
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
      args:
        # Image based on node:16-alpine
        NODE_RELEASE: "16"
        DEBIAN_RELEASE: bullseye
        # Public URL to access the the backend from the clients webbrowser
        # e.g. https://my-monitor-db.example.org
        NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
        # Public websocket URL to access the backend from the clients webbrowser
        # e.g. wss://my-monitor-db.example.org
        NEXT_PUBLIC_BACKEND_WS: ${BACKEND_WS}
    container_name: jobmon_frontend_test_env
    volumes:
      # Frontend source code
      - type: bind
        source: ./frontend
        target: /app
      # Cache for node modules
      - type: volume
        source: jobmon_frontend_nodes_modules_test
        target: /app/node_modules
      # Cache for next.js folder
      - type: volume
        source: jobmon_frontend_nextjs_test
        target: /app/.next

  jobmon_backend_tests:
    restart: no
    build:
      context: ./backend
      dockerfile: Dockerfile.test
      args:
        # Image based on golang:1.20-bullseye
        GOLANG_RELEASE: "1.20"
        DEBIAN_RELEASE: bullseye
    container_name: jobmon_backend_test_env
    volumes:
      # Backend source code
      - type: bind
        source: ./backend
        target: /app
      # Cache for go builds
      - type: volume
        source: jobmon_backend_cache_go_build_test
        target: /root/.cache/go-build
      # Cache for go packages
      - type: volume
        source: jobmon_backend_cache_go_packages_test
        target: /go

volumes:
  jobmon_backend_cache_go_build_test:
    name: jobmon_backend_cache_go_build_test
  jobmon_backend_cache_go_packages_test:
    name: jobmon_backend_cache_go_packages_test
  jobmon_frontend_nextjs_test:
    name: jobmon_frontend_nextjs_test
  jobmon_frontend_nodes_modules_test:
    name: jobmon_frontend_nodes_modules_test
